<a href="https://colab.research.google.com/github/Enrico68/meta-analysis/blob/main/first_steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Funzione `elevami al quadrato`


```
# questa funzione dimostra il quadrato del numero 0-5
def squared (x=10):
  return x**2
for ii in range (6):
  print(ii,squared (ii))
print(squared())
```



In [1]:
# @title Testo del titolo predefinito
def squared (x=10):
  return x**2
for ii in range (6):
  print(ii,squared (ii))
print(squared())

0 0
1 1
2 4
3 9
4 16
5 25
100


In [2]:
myList=['abc', 'def', 'ghij']


In [3]:
myList.append('klm')

In [4]:
myList

['abc', 'def', 'ghij', 'klm']

In [5]:
myList2=[1,2,3]
myList3=[4,5,6]
myList2+myList3

[1, 2, 3, 4, 5, 6]

In [6]:
import numpy as np
myArray2=np.array(myList2)
myArray3=np.array(myList3)


In [7]:
myArray3 + myArray2

array([5, 7, 9])

In [8]:
# Questo serve ad eseguire il prodotto scalare di un array
myArray2.dot(myArray3)
myArray2 @ myArray3

32

In [9]:
myTuple=('abc', np.arange(0,3,0.2), 2.5)


In [10]:
myTuple[2]

2.5

In [11]:
myTuple[1]

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8])

In [12]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [13]:
np.arange(0,5,1, dtype=int)

array([0, 1, 2, 3, 4])

In [14]:
import pandas as pd

In [16]:
state = pd.read_csv('state.csv')

In [17]:
state['Population'].mean()

6162876.3

In [20]:
from scipy import stats
stats.trim_mean(state['Population'],0.1)

4783697.125